### PR TITLE
Implements of Wasserstein Divergence for GANs

### PR DESCRIPTION
**Pull request by Pinnh**

### CODE REVIEW

**Comment by Pinnh** [comment]
Hi， I implemented the Wasserstein Divergence for GANs(wgan_div) and tested . the performance of wgan_div on face super-resolution and mnist  is as same as wgan_gp .

**Comment by eriklindernoren** [comment]
That's awesome. Do you have some image samples we can add to the README?

**Comment by Pinnh** [comment]
Sure. In order to be consistent with previous samples, mnist image samples have committed to the assets.

**Comment by eriklindernoren** [comment]
If you have samples from super-resolution that would be even better. Would like to have more diverse (not only MNIST) samples in the README.

**Comment by eriklindernoren** [comment]
Cool, thanks! Merging

**Pull request merged**
